title: Site Name
email: me@email.com
author: Name
description: #
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima

sass:
  compressed: true
  
gems:
  - jekyll-feed
  
exclude:
  - Gemfile
  - Gemfile.lock